package excecao;

public class ChecadaVsNÃ£oChecada {
	
	public static void main(String[] args) {
		
		gerarErro1();
		
		gerarErro2();
		
		System.out.println("Fim :)");
	}
	
	static void gerarErro1() {
		throw new RuntimeException("Ocorreu um erro #01");
	}
	
	static void gerarErro2() {
		throw new Exception("Ocorreu um erro #02");
	}
}
